################################################################################
# title: Edit Values of the Fire Data 
# author: Mehmet Göktuğ Öztürk
# project: Rethinking lightning-induced fires: Spatial variability and 
#          implications for management policies
################################################################################

# load packages ----------------------------------------------------------------
libs <- c("readr", "dplyr", "tidyr", "sf")
sapply(libs, require, character.only = TRUE)

# read fire data and wrangle them ----------------------------------------------
fire <- read_csv("./data/output/ogm/fire_data/fire_tidy1.csv", trim_ws = TRUE)

# edit obm
fire_obm <- fire |> 
  mutate(
    obm = case_when(
      obm == "antalta" ~ "antalya",
      obm == "s.urfa" ~ "sanliurfa",
      obm == "adapazari" ~ "sakarya",
      obm == "k.maras" ~ "kahramanmaras",
      .default = obm
    ))

# edit oim
fire_oim <- fire_obm |>
  mutate(
    oim = case_when(
      oim == "a.k.hisar" ~ "afyonkarahisar",
      oim == "a.karahisar" ~ "afyonkarahisar",
      oim == "a.madeni" ~ "akdagmadeni",
      oim == "acipayan" ~ "acipayam",
      oim == "afyin" ~ "afyonkarahisar",
      oim == "afyon" ~ "afyonkarahisar",
      oim == "afyyon" ~ "afyonkarahisar",
      oim == "akcaova" ~ "akcakoca",
      oim == "akkkus" ~ "akkus",
      oim == "alamdag" ~ "kanlica",
      oim == "alemdag" ~ "kanlica",
      oim == "antakta" ~ "antakya",
      oim == "antep" ~ "gaziantep",
      oim == "arnavutkoy" ~ "istanbul",
      oim == "asar" ~ "antalya",
      oim == "balya" ~ "ivrindi",
      oim == "bargama" ~ "bergama",
      oim == "berganma" ~ "bergama",
      oim == "biyabat" ~ "boyabat",
      oim == "caanakkale" ~ "canakkale",
      oim == "canakale" ~ "canakkale",
      oim == "catalzetin" ~ "catalzeytin",
      oim == "cayagzi" ~ "bafra",
      oim == "cayiralan" ~ "yozgat",
      oim == "ceres" ~ "cerkes",
      oim == "cubuk" ~ "ankara",
      oim == "dikmen" ~ "gerze",
      oim == "diyarbaki" ~ "diyarbakir",
      oim == "dursunbeyli" ~ "dursunbey",
      oim == "egridir" ~ "egirdir",
      oim == "erba" ~ "erbaa",
      oim == "erdemit" ~ "edremit",
      oim == "erzin" ~ "dortyol",
      oim == "fenertepe" ~ "istanbul",
      oim == "fetiye" ~ "fethiye",
      oim == "g.antep" ~ "gaziantep",
      oim == "g.hacikoy" ~ "amasya",
      oim == "gedik" ~ "gediz",
      oim == "gelibolu" ~ "canakkale",
      oim == "gevye" ~ "geyve",
      oim == "gole" ~ "ardahan",
      oim == "goynucek" ~ "amasya",
      oim == "gumusdere" ~ "geyve",
      oim == "guneysinir" ~ "konya",
      oim == "gurdes" ~ "gordes",
      oim == "hedek" ~ "hendek",
      oim == "hisar" ~ "golhisar",
      oim == "honaz" ~ "denizli",
      oim == "hopa" ~ "arhavi",
      oim == "horasan" ~ "erzurum",
      oim == "ilgin" ~ "konya",
      oim == "ilis" ~ "kilis",
      oim == "k.burgaz" ~ "istanbul",
      oim == "k.dere" ~ "kavaklidere",
      oim == "kavaklider" ~ "kavaklidere",
      oim == "k.dz.eregli" ~ "eregli",
      oim == "k.eregli" ~ "eregli",
      oim == "karadeniz eregli" ~ "eregli",
      oim == "kdz. eregli" ~ "eregli",
      oim == "kdz.eregli" ~ "eregli",
      oim == "k.hamam" ~ "kizilcahamam",
      oim == "k.maras" ~ "kahramanmaras",
      oim == "kadipinari" ~ "akdagmadeni",
      oim == "kandira" ~ "izmit",
      oim == "karacam" ~ "vezirkopru",
      oim == "karacasu" ~ "karasu",
      oim == "katasu" ~ "karasu",
      oim == "kemerburgaz" ~ "istanbul",
      oim == "kimluca" ~ "kumluca",
      oim == "kirka" ~ "eskisehir",
      oim == "kocegiz" ~ "koycegiz",
      oim == "korkyteli" ~ "korkuteli",
      oim == "koyuhisar" ~ "koyulhisar",
      oim == "m.k.pasa" ~ "mustafakemalpasa",
      oim == "m.kemalpasa" ~ "mustafakemalpasa",
      oim == "manvgat" ~ "manavgat",
      oim == "merzifon" ~ "amasya",
      oim == "mahalliccik" ~ "mihaliccik",
      oim == "mihalliccik" ~ "mihaliccik",
      oim == "mudurbu" ~ "mudurnu",
      oim == "mustafa k.p." ~ "mustafakemalpasa",
      oim == "nalihan" ~ "nallihan",
      oim == "nazlli" ~ "nazilli",
      oim == "ofyon" ~ "afyonkarahisar",
      oim == "orhangazi" ~ "bursa",
      oim == "osmaniye osmaniye" ~ "osmaniye",
      oim == "pazanti" ~ "pozanti",
      oim == "pazarcamli" ~ "pazar",
      oim == "s.karaagac" ~ "egirdir",
      oim == "s.karahisar" ~ "sebinkarahisar",
      oim == "s.urfa" ~ "sanliurfa",
      oim == "samatlaar" ~ "samatlar",
      oim == "sarikoy" ~ "bandirma",
      oim == "sarfanbolu" ~ "safranbolu",
      oim == "saricam" ~ "adana",
      oim == "sindirli" ~ "sindirgi",
      oim == "sorgun" ~ "yozgat",
      oim == "sultanbeyli" ~ "kanlica",
      oim == "taskesti" ~ "mudurnu",
      oim == "tasova" ~ "amasya",
      oim == "tokal" ~ "tokat",
      oim == "turkeri" ~ "turkeli",
      oim == "ula" ~ "mugla",
      oim == "urla" ~ "menderes",
      oim == "v.kopru" ~ "vezirkopru",
      oim == "yahyali" ~ "kayseri",
      oim == "yiglica" ~ "yigilca",
      .default = oim
    )
  )

# edit ois
fire_ois <- fire_oim |> 
  mutate(
    ois = case_when(
      ois == "19 mayis" ~ "ondokuzmayis",
      ois == "19.may" ~ "ondokuzmayis",
      ois == "19.may." ~ "ondokuzmayis",
      ois == "19.mayis" ~ "ondokuzmayis",
      ois == "a alagir" ~ "asagialakir",
      ois == "a.alakir" ~ "asagialakir",
      ois == "a.avsar" ~ "aksu-avsar",
      ois == "a.cayi" ~ "alancayi",
      ois == "a.cigil" ~ "asagicigil",
      ois == "a.dagmadeni" ~ "akdagmadeni",
      ois == "a.gokdere" ~ "asagigokdere",
      ois == "a.k.hisar" ~ "afyonkarahisar",
      ois == "a.karahisar" ~ "afyonkarahisar",
      ois == "a.pinari" ~ "avcipinari",
      ois == "a.yeri" ~ "ahmetyeri",
      ois == "adadag" ~ "adadagi",
      ois == "adalan" ~ "adala",
      ois == "adrasan mp" ~ "adrasan",
      ois == "adrasen" ~ "adrasan",
      ois == "af.k.hisar" ~ "afyonkarahisar",
      ois == "afyan" ~ "afyonkarahisar",
      ois == "afyon" ~ "afyonkarahisar",
      ois == "ahlatdagi" ~ "ahlatdag",
      ois == "akagoz" ~ "alagoz",
      ois == "akcakoca" ~ "akcaova",
      ois == "aksu avsar" ~ "aksu-avsar",
      ois == "aksuavsar" ~ "aksu-avsar",
      ois == "alabardo" ~ "alabarda",
      ois == "alaborda" ~ "alabarda",
      ois == "alamdag" ~ "alemdag",
      ois == "altinbas" ~ "altintas",
      ois == "altinkas" ~ "altinkum",
      ois == "altitas" ~ "altintas",
      ois == "anbardagi" ~ "ambardagi",
      ois == "antalta" ~ "antalya",
      ois == "ardicdag" ~ "ardicdagi",
      ois == "arsiz" ~ "ulucinar",
      ois == "aslankoy" ~ "arslankoy",
      ois == "aser" ~ "asar",
      ois == "aslanaga" ~ "aslanapa",
      ois == "asagiasakir" ~ "asagialakir",
      ois == "asagi alakir" ~ "asagialakir",
      ois == "asagialkir" ~ "asagialakir",
      ois == "avva" ~ "agva",
      ois == "b. camurlu" ~ "buyukcamurlu",
      ois == "b.camurlu" ~ "buyukcamurlu",
      (oim == "eskisehir" & ois == "b.yayla") ~ "buyukyayla",
      (oim == "antalya" & ois == "b.yayla") ~ "burmahanyayla",
      (oim == "antalya" & ois == "b. yayla") ~ "burmahanyayla",
      ois == "b.eceli" ~ "buyukeceli",
      ois == "b.orhan" ~ "buyukorhan",
      ois == "babadagi" ~ "babadag",
      ois == "bademlli" ~ "bademli",
      ois == "bagkaya" ~ "bagyaka",
      ois == "baglamis" ~ "baslamis",
      ois == "balisik" ~ "balikisik",
      ois == "bayramici" ~ "bayramic",
      ois == "bayramoren" ~ "kursunlu",
      ois == "bazarkoy" ~ "pazarkoy",
      ois == "bektesaga" ~ "bektasaga",
      ois == "belan" ~ "belen",
      ois == "bellibel" ~ "bellibol",
      ois == "bendler" ~ "bentler",
      ois == "bergame" ~ "bergama",
      ois == "bey.seh.gol.mp" ~ "beysehirgolu mp.",
      ois == "beydaglari.s.m.p." ~ "beydaglari mp.",
      ois == "beydaglari mp" ~ "beydaglari mp.",
      ois == "beydagi" ~ "beydag",
      ois == "bgoksun" ~ "goksun",
      ois == "borabay" ~ "boraboy",
      ois == "bornava" ~ "karsiyaka",
      ois == "bornova" ~ "karsiyaka",
      ois == "bozhuyuk" ~ "bozhoyuk",
      ois == "bucakisla" ~ "bucakkisla",
      ois == "bulanikdere" ~ "igneada",
      ois == "buldendere" ~ "buldandere",
      ois == "burhandagi" ~ "burhandag",
      ois == "burmahan yayla" ~ "burmahanyayla",
      ois == "burmayayla" ~ "burmahanyayla",
      ois == "burmuhanyayla" ~ "burmahanyayla",
      ois == "burduk" ~ "burnuk",
      ois == "buyukduz arastirma" ~ "buyukduz ar.orm",
      ois == "c.dere" ~ "cehennemdere",
      ois == "c.han-edremit" ~ "cinarlihan",
      ois == "c.hemsin" ~ "camlihemsin",
      ois == "c.hisar" ~ "cavdarhisar",
      ois == "c.koy" ~ "cerkezkoy",
      ois == "c.zeytin" ~ "catalzeytin",
      ois == "caldagi" ~ "caldag",
      ois == "cahillibuk" ~ "caltilibuk",
      ois == "caltibuktu" ~ "caltilibuk",
      ois == "caltikbuk" ~ "caltilibuk",
      ois == "caltilibuku" ~ "caltilibuk",
      ois == "camdagi1917" ~ "camdagi 1917",
      ois == "camuca" ~ "camucu",
      ois == "camurlu" ~ "buyukcamurlu",
      ois == "cansu" ~ "camsu",
      ois == "capalan" ~ "camalan",
      ois == "casur" ~ "casur",
      ois == "catakalan" ~ "catalan",
      ois == "cataldere" ~ "catalan",
      ois == "catali" ~ "catak",
      ois == "catalzetin" ~ "catalzeytin",
      ois == "cayagizi" ~ "cayagzi",
      ois == "catyiralan" ~ "cayiralan",
      ois == "caybasi" ~ "unye",
      ois == "caycinge" ~ "yesilcay",
      ois == "cezibeli" ~ "cetibeli",
      ois == "cicekle" ~ "cicekli",
      ois == "ciflik" ~ "ciftlik",
      ois == "cinarlikoru" ~ "cinarlidere",
      ois == "courler" ~ "cogurler",
      ois == "cumayeri" ~ "cumayani",
      ois == "d.carsamba" ~ "derecarsamba",
      ois == "d.dere" ~ "degirmendere",
      ois == "d.egrek" ~ "degirmenegrek",
      ois == "d.hisar" ~ "doganhisar",
      ois == "d.konak" ~ "devecikonak",
      ois == "d.k.m.park" ~ "koprulukanyon mp.",
      ois == "d.koruma mp." ~ "koprulukanyon mp.",
      ois == "dkmp" ~ "koprulukanyon mp.",
      ois == "d.pinar" ~ "dumlupinar",
      ois == "dademday" ~ "dedemdag",
      ois == "daskiri" ~ "dazkiri",
      ois == "davrekani" ~ "devrekani",
      ois == "dedemdagi" ~ "dedemdag",
      ois == "degirmeciler" ~ "degirmenciler",
      ois == "degirmensaz" ~ "degirmisaz",
      ois == "denizciler" ~ "iskenderun",
      ois == "denizovasi" ~ "denizova",
      ois == "derme" ~ "demre",
      ois == "desdek" ~ "destek",
      ois == "desemealti" ~ "dosemealti",
      ois == "devecibanak" ~ "devecikonak",
      (oim == "ilgaz") & (ois == "devrek") ~ "devrez",
      ois == "dimcayi" ~ "dim",
      ois == "dirahna" ~ "drahna",
      ois == "diranas" ~ "erfelek",
      ois == "dirmi" ~ "dirmil",
      ois == "doancay" ~ "dogancay",
      ois == "doyracik" ~ "poyracik",
      ois == "dumlupunar" ~ "dumlupinar",
      ois == "dursunbeyli" ~ "dursunbey",
      ois == "duzagac" ~ "duzdag",
      ois == "duzlercani" ~ "duzlercami",
      ois == "ecabat" ~ "eceabat",
      ois == "ecebat" ~ "eceabat",
      ois == "efleni" ~ "eflani",
      ois == "egri" ~ "egni",
      ois == "egridir" ~ "egirdir",
      ois == "egrigazdagi" ~ "egrigozdagi",
      ois == "egrigoz" ~ "egrigozdagi",
      ois == "egriozdagi" ~ "egrigozdagi",
      ois == "elekcam" ~ "elekcami",
      ois == "erba" ~ "erbaa",
      ois == "erenlerkoy" ~ "erenlerkos",
      ois == "erenlerkoz" ~ "erenlerkos",
      ois == "ernelerkos" ~ "erenlerkos",
      ois == "erfekel" ~ "erfelek",
      ois == "evciler" ~ "kazdagi",
      ois == "f.ova" ~ "egriova",
      ois == "f.pinari" ~ "findikpinari",
      ois == "fenertep" ~ "fenertepe",
      ois == "furucek" ~ "burucek",
      ois == "g.antep" ~ "gaziantep",
      ois == "g.dag" ~ "guneydag",
      ois == "g.dokuncun" ~ "g.dokurcun",
      ois == "g.dokurcan" ~ "g.dokurcun",
      ois == "g.emir" ~ "gaziemir",
      ois == "g.hacikoy" ~ "gumushacikoy",
      ois == "g.marmara" ~ "golmarmara",
      ois == "g.o.p" ~ "istanbul",
      ois == "g.o.pasa" ~ "istanbul",
      ois == "g.osmanpasa" ~ "istanbul",
      ois == "gaziosmanpasa" ~ "istanbul",
      ois == "g.tarihi.m.p" ~ "canakkale savaslari ab.",
      ois == "g.y.t.mp" ~ "canakkale savaslari ab.",
      ois == "g.yayla" ~ "gurgenyayla",
      ois == "gerdes" ~ "gordes",
      ois == "gevye" ~ "geyve",
      ois == "gireun" ~ "giresun",
      ois == "gocesu" ~ "gokcesu",
      ois == "gokcebag" ~ "gokcedag",
      ois == "goldagi" ~ "goldag",
      ois == "goldgi" ~ "goldag",
      ois == "goluk" ~ "golcuk",
      ois == "gop(arnavutkoy)" ~ "arnavutkoy",
      ois == "goreli" ~ "gorele",
      ois == "gozde" ~ "gozne",
      ois == "goztepe" ~ "goktepe",
      ois == "gumelidere" ~ "gumeledere",
      ois == "gumeli" ~ "gumelik",
      ois == "gumuldere" ~ "ozdere",
      ois == "gumldur" ~ "ozdere",
      ois == "gumuldur" ~ "ozdere",
      ois == "gundogdu" ~ "gundogmus",
      ois == "guneyda" ~ "guneydag",
      ois == "guneydogu" ~ "guneydag",
      ois == "guneydokurcun" ~ "g.dokurcun",
      ois == "guneykoy" ~ "guney",
      ois == "guneytepe" ~ "guveytepe",
      ois == "gunoren" ~ "gungoren",
      ois == "gurdes" ~ "gordes",
      ois == "guven" ~ "guvem",
      ois == "guveytine" ~ "guveytepe",
      ois == "guynucek" ~ "goynucek",
      ois == "h.beyli" ~ "hasanbeyli",
      ois == "h.mahmut" ~ "hacimahmut",
      ois == "halik" ~ "hafik",
      ois == "harmandali" ~ "harmancik",
      ois == "hazat" ~ "hozat",
      ois == "hekimham" ~ "hekimhan",
      ois == "hemsin" ~ "camlihemsin",
      ois == "hinis" ~ "horasan",
      ois == "horzum kozan" ~ "horzum",
      ois == "hozan" ~ "honaz",
      ois == "i.pasa" ~ "ismetpasa",
      ois == "iclaline" ~ "iclaliye",
      ois == "igdirdag" ~ "igdirdagi",
      ois == "inceburun" ~ "sinop",
      ois == "isen" ~ "esen",
      ois == "isknderun" ~ "iskenderun",
      ois == "ismetpese" ~ "ismetpasa",
      ois == "ivindi" ~ "ivrindi",
      ois == "k eltepe" ~ "keltepe",
      ois == "k.adrasan" ~ "adrasan",
      ois == "k.agac" ~ "kirkagac",
      ois == "k.ali" ~ "kocaali",
      ois == "k.burgaz" ~ "istanbul",
      ois == "k.bortlen" ~ "karabortlen",
      ois == "k.baraji" ~ "kemerbaraji",
      ois == "k.dere" ~ "kavaklidere",
      ois == "k.g.m.p" ~ "kovadagolu mp.",
      ois == "k.hamam" ~ "kizilcahamam",
      ois == "k.hani" ~ "kadinhani",
      ois == "k.hisar" ~ "karacahisar",
      ois == "k.k milli parki" ~ "koprulukanyon mp.",
      ois == "k.k. milli parki" ~ "koprulukanyon mp.",
      ois == "k.k.m.p" ~ "koprulukanyon mp.",
      ois == "k.k.m.p." ~ "koprulukanyon mp.",
      ois == "k.k.m.park" ~ "koprulukanyon mp.",
      ois == "k.k.millipark" ~ "koprulukanyon mp.",
      ois == "k.k.park" ~ "koprulukanyon mp.",
      ois == "k.kalyon" ~ "koprulukanyon mp.",
      ois == "k.kanyon" ~ "koprulukanyon mp.",
      ois == "kop. kan. mp" ~ "koprulukanyon mp.",
      ois == "koprulu kanyon mp" ~ "koprulukanyon mp.",
      ois == "k.p.m" ~ "koprulukanyon mp.",
      (oim == "tasagil" & ois == "k.millipark") ~ "koprulukanyon mp.",
      ois == "kk millipark" ~ "koprulukanyon mp.",
      ois == "kop. kan. mp" ~ "koprulukanyon mp.",
      ois == "koprulu kanyon mp" ~ "koprulukanyon mp.",
      ois == "k.m.p" ~ "beydaglari mp.",
      ois == "k.m.p.m" ~ "beydaglari mp.",
      (obm == "antalya" & ois == "k.m.park") ~ "beydaglari mp.",
      ois == "k.m.parki" ~ "beydaglari mp.",
      ois == "k.mil.park" ~ "beydaglari mp.",
      ois == "k.milli park" ~ "beydaglari mp.",
      ois == "k.millipark" ~ "beydaglari mp.",
      ois == "kemer  m.p." ~ "beydaglari mp.",
      ois == "kemer  mp." ~ "beydaglari mp.",
      ois == "kemer m.p" ~ "beydaglari mp.",
      ois == "kemer millipark" ~ "beydaglari mp.",
      ois == "kemer mp" ~ "beydaglari mp.",
      ois == "kemer mp." ~ "beydaglari mp.",
      ois == "kmer mp" ~ "beydaglari mp.",
      (obm == "aydin" & ois == "k.m.park") ~ "dilekyarimadasi mp.",
      ois == "kusadasi m.p." ~ "dilekyarimadasi mp.",
      ois == "kusadasi mp" ~ "dilekyarimadasi mp.",
      ois == "kusadasi(m.p.)" ~ "dilekyarimadasi mp.",
      ois == "k.kocan" ~ "karakocan",
      ois == "k.kopru" ~ "kemerkopru",
      ois == "k.maras" ~ "kahramanmaras",
      ois == "k.mursel" ~ "karamursel",
      ois == "k.oren" ~ "karacaoren",
      ois == "k.pasa" ~ "kemalpasa",
      ois == "k.sile" ~ "kurucasile",
      ois == "k.suyu" ~ "kartalsuyu",
      ois == "kafcaz" ~ "kofcaz",
      ois == "kalan" ~ "kavakalan",
      ois == "kapukaya" ~ "kapikaya",
      (oim == "akhisar" & ois == "karaagac") ~ "kirkagac",
      ois == "karacahisr" ~ "karacahisar",
      ois == "karacay" ~ "samandag",
      ois == "karadana" ~ "karadona",
      ois == "karadoga" ~ "karaduga",
      ois == "karakac" ~ "karakas",
      ois == "karakiz" ~ "karakuz",
      ois == "karakus" ~ "karakuz",
      ois == "karms" ~ "karmis",
      ois == "karpuslu" ~ "karpuzlu",
      ois == "katrandag" ~ "katrandagi",
      ois == "kavaklider" ~ "kavaklidere",
      ois == "kayaderesi" ~ "kayadere",
      ois == "kazcagiz" ~ "kozcagiz",
      ois == "kazdag" ~ "kazdagi",
      ois == "kazdere" ~ "kozdere",
      ois == "kdz.eregli" ~ "eregli",
      ois == "kemer baraji" ~ "kemerbaraji",
      ois == "kemerkoru" ~ "kemerkopru",
      ois == "kepsut-kirec" ~ "kepsut",
      ois == "kirac" ~ "kirec",
      ois == "kiragva" ~ "kiravga",
      ois == "kirazdag" ~ "kirazdagi",
      ois == "kirikan" ~ "kirikhan",
      ois == "kirkbidak" ~ "kirkbudak",
      ois == "kizildag mp" ~ "kizildag mp.",
      ois == "kizlcahamam" ~ "kizilcahamam",
      ois == "kobacam" ~ "kabacam",
      ois == "kocaeli" ~ "kocaali",
      ois == "kocamursel" ~ "karamursel",
      ois == "kocnli" ~ "kocanli",
      ois == "komurgulu" ~ "komurgolu",
      ois == "korucuova" ~ "kurucaova",
      ois == "korudag" ~ "korudagi",
      ois == "koruluk" ~ "korucuk",
      ois == "kosedag" ~ "kosdag",
      ois == "kovada" ~ "kovada cayi arb.",
      ois == "kovada mp" ~ "kovadagolu mp.",
      ois == "kovadagolu" ~ "kovadagolu mp.",
      ois == "koyuhbaba" ~ "koyunbaba",
      ois == "kozagac" ~ "kozagaci",
      ois == "kozlu" ~ "yayla",
      ois == "kravga" ~ "kiravga",
      ois == "kratepe" ~ "karatepe",
      ois == "kundus" ~ "kunduz",
      ois == "kurdere" ~ "kurdese",
      ois == "kurdesen" ~ "kurdese",
      ois == "kurtcemeni" ~ "kurtcimeni",
      ois == "kurucuova" ~ "kurucaova",
      ois == "k.m.park" ~ "dilekyarimadasi mp.",
      ois == "kusadasi mp." ~ "dilekyarimadasi mp.",
      ois == "kuzalic" ~ "kuzaluc",
      ois == "lalapasa" ~ "edirne",
      ois == "lengume-mp" ~ "lengume",
      ois == "m.cayi" ~ "mentese",
      ois == "m.k.pasa" ~ "mustafakemalpasa",
      ois == "m.kemalpasa" ~ "mustafakemalpasa",
      ois == "m.kemelpasa" ~ "mustafakemalpasa",
      ois == "marmaris.m.p" ~ "marmaris mp.",
      ois == "marmaris(mp)" ~ "marmaris mp.",
      ois == "mazidag" ~ "mazidagi",
      ois == "medra" ~ "madra",
      ois == "menemem" ~ "menemen",
      ois == "menetesecayi" ~ "mentesecayi",
      ois == "mentescayi" ~ "mentesecayi",
      ois == "mentese cayi" ~ "mentesecayi",
      ois == "merguze(murguze)" ~ "merguze",
      ois == "merzfon" ~ "merzifon",
      ois == "merzifin" ~ "merzifon",
      ois == "mihalliccik" ~ "mihaliccik", 
      ois == "mihallicik" ~ "mihaliccik", 
      ois == "mityat" ~ "midyat", 
      ois == "mollafeneri" ~ "mollafenari", 
      ois == "mumtdagi" ~ "muratdagi", 
      ois == "muratdere31.07.07" ~ "muratdere", 
      ois == "nannam" ~ "namnam", 
      ois == "narlisaray" ~ "nallisaray", 
      ois == "narzum" ~ "horzum", 
      ois == "nurdag" ~ "nurdagi", 
      ois == "oran" ~ "oren", 
      ois == "p.hisar" ~ "pinarhisar", 
      ois == "pamakkale" ~ "pamukkale", 
      ois == "pempecik" ~ "pembecik", 
      ois == "persambe" ~ "persembe", 
      ois == "poyrazcik" ~ "poyracik", 
      ois == "puturye" ~ "poturge", 
      ois == "puturge" ~ "poturge", 
      ois == "rezin" ~ "erzin", 
      ois == "s.hisar" ~ "seferihisar", 
      ois == "s.karaagac" ~ "sarkikaraagac", 
      ois == "s.karahisar" ~ "sebinkarahisar", 
      (oim == "taskopru" & ois == "s.kaya") ~ "sarikaya", 
      (oim == "gordes" & ois == "s.kaya") ~ "sahinkaya", 
      ois == "s.kochisar" ~ "bala", 
      ois == "s.pasa" ~ "sinanpasa", 
      (oim == "kutahya" & ois == "s.pinar") ~ "sabuncupinar", 
      (oim == "bursa" & ois == "s.pinar") ~ "sogukpiner", 
      ois == "s.tepe" ~ "savastepe",
      ois == "s.urfa" ~ "sanliurfa",
      ois == "sagrin" ~ "sagirin",
      ois == "sakran" ~ "yenisakran",
      ois == "samandagi" ~ "samandag",
      ois == "sapane" ~ "saphane",
      ois == "sargol" ~ "sarigol",
      ois == "saruhan" ~ "saruhanli",
      ois == "saruhanliu" ~ "saruhanli",
      ois == "savran" ~ "savrun",
      ois == "saydan" ~ "seydan",
      ois == "seferhisar" ~ "seferihisar",
      ois == "sellale" ~ "selale",
      ois == "seyirgazi" ~ "seyitgazi",
      ois == "sipahi dagi" ~ "sipahidag",
      ois == "sipahiagi" ~ "sipahidag",
      ois == "sipahidagi" ~ "sipahidag",
      ois == "sipayidagi" ~ "sipahidag",
      ois == "sipahitasi" ~ "sipahidag",
      ois == "s.dagi" ~ "sipahidag",
      ois == "sivriklubeler" ~ "sivrikulubeler",
      ois == "sivrikuleler" ~ "sivrikulubeler",
      ois == "soganlicayi" ~ "soganlicay",
      ois == "sorgun(eymir)" ~ "sorgun",
      ois == "sunnet golu" ~ "sunnetgolu",
      (oim == "tasagil" & ois == "b.yayla") ~ "burmahanyayla",
      (oim == "tasagil" & ois == "b. yayla") ~ "burmahanyayla",
      ois == "tefenli" ~ "tefenni",
      ois == "tekekoy" ~ "tekkekoy",
      ois == "tenisehir" ~ "yenisehir",
      ois == "tira" ~ "tire",
      ois == "tucbilek" ~ "tuncbilek",
      ois == "turgul" ~ "turgut",
      ois == "turkeri" ~ "turkeli",
      ois == "u.burc" ~ "uzuncaburc",
      ois == "uzunburc" ~ "uzuncaburc",
      ois == "v.aktas" ~ "vakifaktas",
      ois == "y.a.selale" ~ "selale",
      ois == "y.alakir" ~ "yukarialakir",
      ois == "y.dere" ~ "yenidere",
      ois == "y.gokdere" ~ "yukarigokdere",
      ois == "y.ovacik" ~ "yesilovacik",
      ois == "y.sahran" ~ "yenisakran",
      ois == "y.sakran" ~ "yenisakran",
      ois == "y.tepe" ~ "yapraktepe",
      ois == "y.tepe-seki" ~ "yapraktepe",
      ois == "yakidibi" ~ "yalcidibi",
      ois == "yalakguz" ~ "yalakkuz",
      ois == "yapratepe" ~ "yapraktepe",
      ois == "yayladag" ~ "yayladagi",
      ois == "yekencidag" ~ "yelkencidag",
      ois == "yelkencedag" ~ "yelkencidag",
      ois == "yelkenci" ~ "yelkencidag",
      ois == "yelkencidagi" ~ "yelkencidag",
      ois == "yelkendag" ~ "yelkencidag",
      ois == "yenicag" ~ "yenicaga",
      ois == "yerseki" ~ "yerkesik",
      ois == "yesilbayir" ~ "yesilbag",
      ois == "yesildere" ~ "yesildag",
      ois == "yuntdag" ~ "yuntdagi",
      ois == "yorse" ~ "yurse",
      ois == "z.ova" ~ "zeytinliova",
      ois == "zeytinova" ~ "zeytinliova",
      .default = ois
    ))

# second control
fire_all <- fire_ois |> 
  mutate(
    oim = case_when(
      (obm == "adana" & ois == "burucek") ~ "pozanti",
      (obm == "adana" & ois == "nevsehir") ~ "nevsehir",
      (obm == "adana" & ois == "nevsehir") ~ "nevsehir",
      (obm == "adana" & ois == "nigde") ~ "nigde",
      (obm == "adana" & ois == "ulukisla") ~ "nigde",
      (obm == "amasya" & ois == "akcay") ~ "vezirkopru",
      (obm == "amasya" & ois == "aydincik") ~ "yozgat",
      (obm == "amasya" & ois == "cekerek") ~ "yozgat",
      (obm == "amasya" & ois == "sorgun") ~ "yozgat",
      (obm == "amasya" & ois == "yozgat") ~ "yozgat",
      (obm == "amasya" & ois == "niksar") ~ "niksar",
      (obm == "amasya" & ois == "akdagmadeni") ~ "akdagmadeni",
      (obm == "ankara" & ois == "k.kale") ~ "kirikkale",
      (obm == "ankara" & ois == "kirsehir") ~ "kirsehir",
      (obm == "ankara" & ois == "kizilcahamam") ~ "kizilcahamam",
      (obm == "ankara" & ois == "millipark") ~ "soguksu mp.",
      (obm == "ankara" & ois == "k.kaman") ~ "kizilcahamam",
      (obm == "antalya" & ois == "beydaglari mp.") ~ "antalya",
      (obm == "antalya" & ois == "beydaglari mp.") ~ "antalya",
      (obm == "antalya" & ois == "dosemealti") ~ "antalya",
      (obm == "antalya" & ois == "doyran") ~ "antalya",
      (obm == "antalya" & ois == "kemer") ~ "antalya",
      (obm == "antalya" & ois == "cakirlar") ~ "antalya",
      (obm == "antalya" & ois == "dim") ~ "alanya",
      (obm == "antalya" & ois == "kargi") ~ "alanya",
      (obm == "antalya" & ois == "sogut") ~ "alanya",
      (obm == "antalya" & ois == "cakirlar") ~ "antalya",
      (obm == "antalya" & ois == "doyran") ~ "antalya",
      (obm == "antalya" & ois == "duzlercami") ~ "antalya",
      (obm == "antalya" & ois == "demre") ~ "finike",
      (obm == "antalya" & ois == "koprulukanyon mp.") ~ "antalya",
      (obm == "antalya" & ois == "manavgat") ~ "manavgat",
      (obm == "balikesir" & ois == "kepsut") ~ "balikesir",
      (obm == "balikesir" & ois == "susurluk") ~ "bandirma",
      (obm == "balikesir" & ois == "canakkale") ~ "canakkale",
      (obm == "balikesir" & ois == "gelendost") ~ "balikesir",
      (obm == "balikesir" & ois == "balya") ~ "balikesir",
      (obm == "balikesir" & ois == "seydan") ~ "sindirgi",
      (obm == "balikesir" & ois == "yuregil") ~ "sindirgi",
      (obm == "bolu" & ois == "kokez") ~ "aladag",
      (obm == "bolu" & ois == "yongali") ~ "gerede",
      (obm == "bursa" & ois == "harmancik") ~ "orhaneli",
      (obm == "bursa" & ois == "yenice") ~ "inegol",
      (obm == "bursa" & ois == "iznik") ~ "bursa",
      (obm == "bursa" & ois == "mahmudiye") ~ "bursa",
      (obm == "canakkale" & ois == "ezine") ~ "ayvacik",
      (obm == "canakkale" & ois == "katrandagi") ~ "can",
      (obm == "canakkale" & ois == "canakkale savaslari ab.") ~ "canakkale",
      (obm == "canakkale" & ois == "malkara") ~ "tekirdag",
      (obm == "canakkale" & ois == "sarkoy") ~ "tekirdag",
      (obm == "canakkale" & ois == "tekirdag") ~ "tekirdag",
      (obm == "canakkale" & ois == "uzunkopru") ~ "edirne",
      (obm == "canakkale" & ois == "yenice") ~ "yenicecanakkale",
      (obm == "denizli" & ois == "cicekli") ~ "eskere",
      (obm == "denizli" & ois == "acipayam") ~ "acipayam",
      (obm == "denizli" & ois == "banaz") ~ "usak",
      (obm == "denizli" & ois == "tavas") ~ "tavas",
      (obm == "denizli" & ois == "gure") ~ "usak",
      (obm == "denizli" & ois == "yenidere") ~ "tavas",
      (obm == "elazig" & ois == "mardin") ~ "mardin",
      (obm == "elazig" & ois == "mazidagi") ~ "mardin",
      (obm == "elazig" & ois == "midyat") ~ "mardin",
      (obm == "elazig" & ois == "savur") ~ "mardin",
      (obm == "elazig" & ois == "bingol") ~ "bingol",
      (obm == "elazig" & ois == "dogansehir") ~ "malatya",
      (obm == "elazig" & ois == "genc") ~ "bingol",
      (obm == "elazig" & ois == "hekimhan") ~ "malatya",
      (obm == "elazig" & ois == "ilica") ~ "bingol",
      (obm == "elazig" & ois == "kigi") ~ "bingol",
      (obm == "elazig" & ois == "malatya") ~ "malatya",
      (obm == "elazig" & ois == "poturge") ~ "malatya",
      (obm == "elazig" & ois == "solhan") ~ "bingol",
      (obm == "elazig" & ois == "batman") ~ "batman",
      (obm == "elazig" & ois == "cizre") ~ "sirnak",
      (obm == "elazig" & ois == "sirnak") ~ "sirnak",
      (obm == "elazig" & ois == "millipak") ~ "munzurvadisi mp.",
      (obm == "elazig" & ois == "millipark") ~ "munzurvadisi mp.",
      (obm == "izmir" & ois == "torbali") ~ "menderes",
      (obm == "izmir" & ois == "bergama") ~ "bergama",
      (obm == "izmir" & ois == "gaziemir") ~ "menderes",
      (obm == "izmir" & ois == "ozdere") ~ "menderes",
      (obm == "izmir" & ois == "karaburun") ~ "menderes",
      (obm == "izmir" & ois == "urla") ~ "menderes",
      (obm == "izmir" & ois == "seferihisar") ~ "menderes",
      (obm == "kahramanmaras" & ois == "sanliurfa") ~ "sanliurfa",
      (obm == "kahramanmaras" & ois == "siverek") ~ "sanliurfa",
      (obm == "kahramanmaras" & ois == "gaziantep") ~ "gaziantep",
      (obm == "kahramanmaras" & ois == "yayladagi") ~ "antakya",
      (obm == "kahramanmaras" & ois == "nurdagi") ~ "gaziantep",
      (obm == "zonguldak" & ois == "kumluca") ~ "ulus",
      (obm == "zonguldak" & ois == "soku") ~ "ulus",
      (obm == "zonguldak" & ois == "eflani") ~ "safranbolu",
      (obm == "zonguldak" & ois == "indere") ~ "safranbolu",
      (obm == "zonguldak" & ois == "safranbolu") ~ "safranbolu",
      (obm == "zonguldak" & ois == "sipahidag") ~ "safranbolu",
      (obm == "zonguldak" & ois == "soganlicay") ~ "safranbolu",
      (obm == "zonguldak" & ois == "karakisla") ~ "safranbolu",
      (obm == "zonguldak" & ois == "ovacuma") ~ "safranbolu",
      (obm == "zonguldak" & ois == "uluyayla") ~ "safranbolu",
      (obm == "mugla" & ois == "esen") ~ "kemer",
      (obm == "mugla" & ois == "kavaklidere") ~ "kavaklidere",
      (obm == "mugla" & ois == "marmaris mp.") ~ "mugla",
      (obm == "mugla" & ois == "bodrum") ~ "milas",
      (obm == "mugla" & ois == "cakmak") ~ "yilanli",
      (obm == "mugla" & ois == "kemer") ~ "kemer",
      (obm == "mugla" & ois == "namnam") ~ "yilanli",
      (obm == "mugla" & ois == "yilanli") ~ "yilanli",
      (obm == "mugla" & ois == "mentese") ~ "kavaklidere",
      (obm == "mugla" & ois == "ula") ~ "mugla",
      (obm == "istanbul" & ois == "silivri") ~ "catalca",
      (obm == "istanbul" & ois == "sariyer") ~ "bahcekoy",
      (obm == "istanbul" & ois == "sultanbeyli") ~ "kanlica",
      (obm == "istanbul" & ois == "malkara") ~ "tekirdag",
      (obm == "istanbul" & ois == "sarkoy") ~ "tekirdag",
      (obm == "istanbul" & ois == "tekirdag") ~ "tekirdag",
      (obm == "istanbul" & ois == "edirne") ~ "edirne",
      (obm == "istanbul" & ois == "istanbul") ~ "istanbul",
      (obm == "istanbul" & ois == "sahilkoy") ~ "sile",
      (obm == "istanbul" & ois == "bahcekoy") ~ "tekirdag",
      (obm == "istanbul" & ois == "cerkezkoy") ~ "tekirdag",
      (obm == "istanbul" & ois == "saray") ~ "tekirdag",
      (obm == "konya" & ois == "beysehirgolu mp.") ~ "konya",
      (obm == "konya" & ois == "aksaray") ~ "aksaray",
      (obm == "konya" & ois == "beysehir") ~ "beysehir",
      (obm == "konya" & ois == "bucakkisla") ~ "karaman",
      (obm == "konya" & ois == "eregli") ~ "karaman",
      (obm == "konya" & ois == "k.karabekir") ~ "karaman",
      (obm == "konya" & ois == "karaman") ~ "karaman",
      .default = oim
    )
  )

# control for data after 2018
fire_all <- fire_all |> 
  mutate(
    obm = case_when(
      obm == "bati akdeniz or.ae." ~ "antalya",
      obm == "bati karadeniz oae." ~ "bolu",
      obm == "d. karadeniz or.ae." ~ "trabzon",
      obm == "ege or.ae." ~ "izmir",
      obm == "ic anadolu or.ae." ~ "ankara",
      obm == "izmit kavakcilik ae" ~ "sakarya",
      obm == "i bolge (istanbul)" ~ "istanbul",
      (obm == "ii bolge(bursa)" & oim == "canakkale") ~ "canakkale",
      (obm == "ii bolge(bursa)" & oim == "balikesir") ~ "balikesir",
      (obm == "ii bolge(bursa)" & oim == "bursa") ~ "bursa",
      (obm == "iv bolge(manisa)" & oim == "mugla") ~ "mugla",
      (obm == "iv bolge(manisa)" & oim == "aydin") ~ "mugla",
      (obm == "iv bolge(manisa)" & oim == "manisa") ~ "izmir",
      (obm == "iv bolge(manisa)" & oim == "mugla") ~ "mugla",
      (obm == "ix bolge (ankara)" & oim == "ankara") ~ "ankara",
      (obm == "ix bolge (ankara)" & oim == "yozgat") ~ "kayseri",
      (obm == "ix bolge (ankara)" & oim == "bolu") ~ "bolu",
      (obm == "v bolge(a.karahisar)" & oim == "afyonkarahisar") ~ "eskisehir",
      (obm == "v bolge(a.karahisar)" & oim == "denizli") ~ "denizli",
      (obm == "vi bolge(burdur)" & oim == "isparta") ~ "isparta",
      (obm == "vi bolge(burdur)" & oim == "antalya") ~ "antalya",
      obm == "vii bolge(adana)" ~ "adana",
      obm == "viii bolge(konya)" ~ "konya",
      obm == "x bolge(sinop)" ~ "kastamonu",
      (obm == "xii bolge(rize)" & oim == "artvin") ~ "artvin",
      (obm == "xii bolge(rize)" & oim == "rize") ~ "rize",
      (obm == "xii bolge(rize)" & oim == "trabzon") ~ "rize",
      obm == "xiii bolge(erzurum)" ~ "erzurum",
      (obm == "xv bolge(malatya)" & oim == "tunceli") ~ "elazig",
      (obm == "xv bolge(malatya)" & oim == "adiyaman") ~ "sanliurfa",
      obm == "hatay" ~ "kahramanmaras",
      (obm == "doga koruma ve" & oim == "adana sube") ~ "adana",
      (obm == "doga koruma ve" & oim == "ankara sube") ~ "ankara",
      (obm == "doga koruma ve" & oim == "balikesir sube") ~ "balikesir",
      (obm == "doga koruma ve" & oim == "baskomutan tarihi") ~ "eskisehir",
      (obm == "doga koruma ve" & oim == "beydaglari sahil milli") ~ "antalya",
      (obm == "doga koruma ve" & oim == "bursa sube") ~ "bursa",
      (obm == "doga koruma ve" & oim == "denizli sube") ~ "denizli",
      (obm == "doga koruma ve" & oim == "dilek yarimadasi-") ~ "mugla",
      (obm == "doga koruma ve" & oim == "manisa milli park") ~ "izmir",
      (obm == "doga koruma ve" & oim == "mugla milli park") ~ "mugla",
      (obm == "doga koruma ve" & oim == "osmaniye sube") ~ "adana",
      (obm == "doga koruma ve" & oim == "tunceli sube") ~ "elazig",
      (obm == "doga koruma ve milli" & oim == "balikesir sube mudurlugu") ~ "balikesir",
      (obm == "doga koruma ve milli" & oim == "baskomutan tarihi milli") ~ "eskisehir",
      (obm == "doga koruma ve milli" & oim == "beydaglari sahil milli") ~ "antalya",
      (obm == "doga koruma ve milli" & oim == "canakkale sube") ~ "canakkale",
      (obm == "doga koruma ve milli" & oim == "denizli sube mudurlugu") ~ "denizli",
      (obm == "doga koruma ve milli" & oim == "dilek yarimadasi-buyuk") ~ "mugla",
      (obm == "doga koruma ve milli" & oim == "isparta sube mudurlugu") ~ "isparta",
      (obm == "doga koruma ve milli" & oim == "manisa milli park") ~ "izmir",
      (obm == "doga koruma ve milli" & oim == "mugla milli park") ~ "mugla",
      (obm == "doga koruma ve milli" & oim == "osmaniye sube mudurlugu") ~ "adana",
      .default = obm
    )
  )

# read forest boundaries to edit obm values and spatialize fire data -----------
ois <- read_sf("./data/output/ogm/boundaries/ois.gpkg")
obm <- read_sf("./data/output/ogm/boundaries/obm.gpkg")

ois_cent <- st_centroid(ois)
ois_join <- st_join(ois_cent, obm)
ois_join <- ois_join |> 
  select(-obm.x) |>
  rename(obm = obm.y) |>
  relocate(obm, .before = "oim")

# join for before 2018
joined_before_18 <- fire_all |>
  filter(year < 2018) |> 
  left_join(
    ois,
    by = c("oim", "ois"), 
    relationship = "many-to-one"
)
joined_before_18 <- joined_before_18 |>
  filter(!st_is_empty(geom)) |>
  select(-obm.y, -x, -y) |>
  rename(obm = obm.x) |>
  st_as_sf()

# join for after 2018
joined_after_18 <- fire_all |> 
  filter(year >= 2018) |> 
  st_as_sf(coords = c("x", "y"), crs = "EPSG:4326") |> 
  st_transform("EPSG:3035") |> 
  _[obm, ] |> 
  (\(.) st_join(ois, .))() |>
  select(-obm.x, -oim.x, -ois.x) |> 
  rename(obm = obm.y, oim = oim.y, ois = ois.y) |> 
  relocate(obm, .before = "primary_cause") |> 
  relocate(oim, .before = "obm") |> 
  relocate(ois, .before = "ois") |> 
  relocate(geom, .after = "burnt_area") |> 
  drop_na(obm)

# merge two tables
fire_joined <- rbind(joined_before_18, joined_after_18)

fire <- st_drop_geometry(fire_joined)

# write data -------------------------------------------------------------------
write_csv(fire, "./data/output/ogm/fire_data/fire_tidy2.csv")
write_sf(fire_joined, "./data/output/ogm/fire_data/fire_tidy2.gpkg")



